blog/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name ='blog'

urlpatterns = [
    path('', views.all_blog, name= 'all_blog'),
    path('<int:blog_id>', views.content, name= 'blog_content'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name= 'home'),
    path('blog/', include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):

    title = models.CharField(max_length=100)
    date = models. DateField()
    url = models.URLField()
    content = models.TextField()
    image = models.ImageField(upload_to = 'blog_image', blank = 'true')

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=220)
    url = models.URLField(blank = 'true')
    image = models.ImageField(upload_to = 'project_image')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blog(request):
    blogs = Blog.objects.all()
    return render(request, "blog/all_blog.html", {'blogs': blogs})

def content(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/blog_content.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, "portfolio/Home.html", {'projects' :projects})

blog/templates/blog/all_blog.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Devaj has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:blog_content' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/blog_content.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.content|safe }}

{% endblock %}

portfolio/templates/portfolio/Home.html
{% extends "portfolio/base.html" %}


{% block content %}
<br>
{% load static %}
<div class="row justify-content-center my-3">
  <div class="col-6">
    <img src="{% static 'portfolio/devaj.jpeg' %}" class="img-fluid dp">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">I am a Full stack Web Developer and Your helper.😊</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2 project" width = "300px" height="175px">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2 project" width = "300px" height="175px">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <title>Devaj</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="200" height="115" alt="Logo" loading="lazy"></a>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/Devajsuryavanshi" target="_blank">Github</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="mailto: devajsuryavanshi@gmail.com" target="_blank">Email</a>
          </li>
          <li>
            <a role="button" href="/blog/" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>